import numpy as np
# print (np.__version__)
a = np.array([1, 2, 3, 4, 5])
# print(type(a))
b = np.array([[1,2,3], [4,5,6]])
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
# print(a.ndim)
# print(b.ndim)
# print(c.ndim)
d = np.array([1,2,3,4])
# print(d[1] + d[3])
e = np.array([[1,2,4,5,78],[3,6,9,0,95]])
# print('4th element of 1st col:', e[1,3])
f = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# print(f[0,1,2])
g = np.array([1.1,2.2,3.3])
newarr = g.astype('i')
# print(newarr.dtype)
h = np.array([1,0,1,0,1])
i = np.array([[1, 2, 3], [4, 5, 6]])
# for x in h:
#     print(x)
# for x in i:
#   for y in x:
#     print(y)
# print(i.shape)
# print(i.ndim)
# print(i.size)
# j = np.zeros(4)
k = np.array([1,2,3,4])
# l = a[np.newaxis, :]
# print(l.shape)
m = np.expand_dims(k, axis=0)
# print(m.shape)
# list_of_coordinates = list(zip(b[0], b[1]))
# for coord in list_of_coordinates:
#     print(coord)
# (np.int64(0), np.int64(0))
# (np.int64(0), np.int64(1))
# (np.int64(0), np.int64(2))
# (np.int64(0), np.int64(3))
# data = np.array([[1, 2], [3, 4]])
# ones = np.ones(6, dtype=int)
# print(data.sum()) 
#ones
# ab = np.array([[1, 2, 3],
#                [4, 5, 6]])
# print(ab.reshape(3,2))
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reverse_arr = np.flip(arr)
# print(reverse_arr)
arr1 = np.arange(3,2,4)
# arr2 = np.arange(arr1)
arr2 = np.arange(10, 30, 5)
# print(np.arange(500))
# print(np.set_printoptions(threshold=500))
a1 = np.array([20, 30, 40, 50])
b1 = np.array([1,2,3,4])
c1 = a1 - b1
# print(a*b)
# print(a.dot(b))
# a = np.ones(3, dtype=np.int32)
# b = np.linspace(0, pi, 3)
# print(b.dtype.name)
# # print(a + b)
# B = np.arange(3)
# print(B)
# print(np.exp(B))
aa = np.arange(6).reshape(2,3)
# print(aa.shape)
# print(aa.dtype.name)
# print(aa.itemsize)
bb = np.array([(1.1,2),(3,4),(5,6.6)])
cc = np.array([[1,2],[3,4]], dtype='complex')
# print(cc)
B  = np.arange(3)
# print(np.exp(B))
for element in b.flat:
    print(element)