import matplotlib
import matplotlib.pyplot as plt
import numpy as np
# print(matplotlib.__version__)
# x= np.array([1,2])
# y= np.array([3,4])
# plt.plot(x,y)
# apoints = np.array([1,2,3,4])
# bpoints = np.array([5,8,6,10])
# plt.plot(apoints, bpoints, 'o')
# cpoints = np.array([1,2,3,4])
# plt.plot(cpoints)
# d =np.array([5,3,4,6])
# plt.plot(d, marker='*', markersize=10, markeredgecolor='red')
# epoints = np.array([1,2,3,4])
# plt.plot(epoints, linestyle = '--')
# fpoints = np.array([5,7,9,11])
# gpoints = np.array([1,2,3,4])
# plt.plot(fpoints, ls = ':',lw = '4')
# plt.plot(gpoints, ls = '--',lw ='2')
# h = np.array([1,2,3,4])
# i = np.array([4,3,2,1])
# plt.xlabel("Ascending")
# plt.ylabel("Descending")
# plt.plot(h,i, marker='o', markersize=10, markeredgecolor='red', ls='--', lw=2, color='green')
# a = np.array([1,2,3,4])
# b = np.array([5,6,7,8])
# plt.subplot(1,2,1)
# plt.plot(a,b)

# a = np.array([9,10,11,12])
# b = np.array([13,14,15,16])
# plt.subplot(1,2,2)
# plt.plot(a,b)
plt.show()
